branch-defaults:
  master:
    environment: dev-env2
    group_suffix: null
environment-defaults:
  dev-env2:
    branch: null
    repository: null
global:
  application_name: seilie2
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
